version: "3.9"
services:

  app-ui:
    container_name: app-ui
    build: ./app-ui/.
    ports:
      - 8080:80
    depends_on:
      - api_service
    networks:
      - app-network

  api_service:
    image: api-service
    container_name: api-service-app
    build: ./api-service/.
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - mongo_db
      - redis_cache
    networks:
      - app-network

  mongo_db:
    image: mongo:focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: helpdev
      MONGO_INITDB_ROOT_PASSWORD: 123456
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
        - "mongodb:/data/db"
    networks:
      - app-network

  redis_cache:
    container_name: redis_cache
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongodb:

networks:
  app-network:
    driver: bridge